version: '3.9'

services:
  bitcoin-core:
    build:
      context: ./bitcoin-core/${DISTRO:-debian}
      dockerfile: Dockerfile
    command:
      -printtoconsole
      -rest
      -rpcallowip=10.211.0.0/16
      -rpcallowip=172.17.0.0/16
      -rpcallowip=192.168.0.0/16
      -rpcpassword=${RPC_PASSWORD}
      -rpcport=8332
      -rpcuser=${RPC_USER}
      -server
      ${EXTRA_ARGS:-}
    ports:
      - 8332:8332
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    volumes:
      - ${DATA_DIR}:/home/bitcoin/.bitcoin
