version: '3.9'

services:
  bitcoin-core:
    build:
      context: ./bitcoin-core/${VERSION_FLAVOUR:-22.0-debian}
      dockerfile: Dockerfile
    command: ${ARGUMENTS}
    ports:
      - ${RPC_PORT}:8332
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/home/bitcoin/.bitcoin
