version: '3.9'

services:
  bitcoin-core:
    build:
      context: ./bitcoin-core/${VERSION_FLAVOUR:-22.0-debian}
      dockerfile: Dockerfile
    command:
      -printtoconsole
      -rest
      -rpcbind=0.0.0.0:8332
      -rpcpassword=${RPC_PASSWORD}
      -rpcuser=${RPC_USER}
      -server
      ${EXTRA_ARGS:-}
    ports:
      - 8332:8332
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/home/bitcoin/.bitcoin
